.\" Manpage for repokeeper.
.\" Contact tiborb95 at gmail dot com, but prefferably use https://aur.archlinux.org/packages/repokeeper or https://github.com/tibor95/repokeeper
.TH man 8 "19 October 2020" "1.0" "repokeeper man page"
.SH NAME
repokeeper \- update AUR packages in you local repository (for Arch Linux)
.SH SYNOPSIS
repokeeper
(No command line switches for now)
.SH DESCRIPTION
repokeeper is python utility that helps you maintain you custom pacman repository. Should be run as regular user, as makepkg
complains if run as root. Accordingly build and repo directories must be writeable to that user.
.SH OPTIONS
No command line options now.
.SH SEE ALSO
n/a
.SH BUGS
No known bugs.
.SH AUTHOR
Tibor Bamhor (tiborb95@gmail.com)